### PR TITLE
Fix parse Error in case sync

### LINKED ISSUE #104: Parse Error at install
While trying to install I get the following error:
```
/Users/abecchis/.zulu/core/zulu
/Users/abecchis/.zulu/core/zulu:2355: parse error near `>&'
/Users/abecchis/.zshrc:335: command not found: zulu
```
```
zsh --version
zsh 5.1.1 (x86_64-apple-darwin15.0.0)
```

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
protect case option with () to prevent parse error

should fix #104

### CODE REVIEW

**Comment by molovo** [comment]
Thanks for the PR, though I do want to look into the error you received a little more before merging this.

I'm not seeing this error in any versions of ZSH I've tried. The syntax before this change is perfectly valid and should not have raised a parse error, which leads me to believe something else is going on.

Would you mind posting a copy of your `.zshrc` (with any sensitive information redacted)? I'd like to try and recreate this in a VM if I can.

Note to self: I really must enable OSX builds on Travis again

**Comment by AdrieanKhisbe** [comment]
No problem.
Could I send it to you via private message though?

**Comment by molovo** [comment]
Absolutely, my email is hi@molovo.co :)

**Comment by AdrieanKhisbe** [comment]
voilà :)

**Comment by molovo** [comment]
Got it, thanks. I'll take a look at this at some point tomorrow

**Comment by AdrieanKhisbe** [comment]
No emergency :)

**Comment by molovo** [comment]
I never managed to get to the bottom of this - spent a while looking at your `.zshrc` but still couldn't recreate the problem. Since this a) is a purely syntactical change, b) fixes the issue, and c) doesn't break the unit tests, I'm going to merge it.

Before I do that, @AdrieanKhisbe could you please rebase your branch on the `next` branch of Zulu, and then change this PR to target the `next` branch. Then it can be included in `v1.5.0`.

**Comment by AdrieanKhisbe** [comment]
Strange Strange. Thanks a lot for the time invested !

I just rebased as you requested :)

**Comment by AdrieanKhisbe** [comment]
Have you a target in mind for 1.5.0?

**Comment by molovo** [comment]
Yeah, the `next` branch please. Then, you can start using it as soon as it's merged by changing `zulu init` in your `.zshrc` to `zulu init --next` since 1.5 might not be released soon

**Review by molovo — APPROVED** [review]

**Comment by molovo** [comment]
Oh, I can change the base myself. Awesome. LGTM. Thanks for the PR @AdrieanKhisbe

**Comment by AdrieanKhisbe** [comment]
I don't know why I thought I couldn't ^^

**Pull request merged**
